<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net8.0;netstandard2.1</TargetFrameworks>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>12</LangVersion>
        <RootNamespace>LayerBaseTask</RootNamespace>
        <GeneratePackageOnBuild Condition="'$(GITHUB_ACTIONS)' != 'true'">true</GeneratePackageOnBuild>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <Title>LayerBase.Task</Title>
        <Authors>扭矩不足</Authors>
        <Description>分层式DI依赖注入框架,附加层级式事件总线与异步事件总线支持</Description>
        <PackageProjectUrl>https://github.com/avaw23112/LayerBase.git</PackageProjectUrl>
        <PackageLicenseUrl>https://github.com/avaw23112/LayerBase</PackageLicenseUrl>
        <RepositoryUrl>https://github.com/avaw23112/LayerBase.git</RepositoryUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <Version>1.4.4</Version>
        <PackageOutputPath>$(MSBuildProjectDirectory)/../nupkgs</PackageOutputPath>
    </PropertyGroup>

    <ItemGroup>
        <None Include="README.md" Pack="true" PackagePath="\"/>
    </ItemGroup>

</Project>
