<Project Sdk="Microsoft.NET.Sdk">

    <!-- 基础工程配置 -->
    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <TargetFrameworks>netstandard2.1;net8.0</TargetFrameworks>
        <LangVersion>12</LangVersion>
        <Title>LayerBase</Title>
        <Authors>扭矩不足</Authors>
        <Description>分层式DI依赖注入框架,附加层级式事件总线与异步事件总线支持</Description>
        <Copyright>MIT</Copyright>
        <PackageProjectUrl>https://github.com/avaw23112/LayerBase.git</PackageProjectUrl>
        <PackageLicenseUrl>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</PackageLicenseUrl>
        <RepositoryUrl>https://github.com/avaw23112/LayerBase.git</RepositoryUrl>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <Version>1.0.1</Version>
    </PropertyGroup>


    <!-- 保留工具目录结构 -->
    <ItemGroup>
        <Folder Include="Tools\" />
    </ItemGroup>

    <!-- 显式排除暂未启用的源/资源 -->
    <ItemGroup>
        <Compile Remove="DI\Service.cs" />
        <Compile Remove="DataStruct\DictionaryTree\**" />
        <EmbeddedResource Remove="DataStruct\DictionaryTree\**" />
        <None Remove="DataStruct\DictionaryTree\**" />
        <Compile Remove="Event\EventLogTracer\**" />
        <EmbeddedResource Remove="Event\EventLogTracer\**" />
        <None Remove="Event\EventLogTracer\**" />
        <Compile Remove="Event\EventStateTrace\**" />
        <EmbeddedResource Remove="Event\EventStateTrace\**" />
        <None Remove="Event\EventStateTrace\**" />
    </ItemGroup>
    <ItemGroup>
      <ProjectReference Include="..\LayerBase.Task\LayerBase.Task.csproj" />
    </ItemGroup>

</Project>
