<Project Sdk="Microsoft.NET.Sdk">

    <!-- 基础工程配置 -->
    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>12</LangVersion>
        <TieredPGO>true</TieredPGO>
        <Title>LayerBase</Title>
        <Authors>扭矩不足</Authors>
        <Description>高性能一体化游戏架构框架。集成模块化层级、轻量级 DI、异步任务(LBTask)与超极速事件总线。专为 Godot/Unity 优化。</Description>
        <Copyright>Apache-2.0</Copyright>
        <PackageProjectUrl>https://github.com/avaw23112/LayerBase</PackageProjectUrl>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/avaw23112/LayerBase</RepositoryUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <GeneratePackageOnBuild Condition="'$(GITHUB_ACTIONS)' != 'true'">true</GeneratePackageOnBuild>
        <Version>1.5.2</Version>
        <TargetFrameworks>net8.0;netstandard2.1</TargetFrameworks>
        <PackageOutputPath>$(MSBuildProjectDirectory)/../nupkgs</PackageOutputPath>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\README.md" Pack="true" PackagePath="\"/>
    </ItemGroup>


    <!-- 保留工具目录结构 -->
    <ItemGroup>
        <Folder Include="Tools\"/>
    </ItemGroup>

    <!-- 显式排除暂未启用的源/资源 -->
    <ItemGroup>
        <Compile Remove="DI\Service.cs"/>
        <Compile Remove="DataStruct\DictionaryTree\**"/>
        <EmbeddedResource Remove="DataStruct\DictionaryTree\**"/>
        <None Remove="DataStruct\DictionaryTree\**"/>
        <Compile Remove="Event\EventLogTracer\**"/>
        <EmbeddedResource Remove="Event\EventLogTracer\**"/>
        <None Remove="Event\EventLogTracer\**"/>
        <Compile Remove="Event\EventStateTrace\**"/>
        <EmbeddedResource Remove="Event\EventStateTrace\**"/>
        <None Remove="Event\EventStateTrace\**"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\LayerBase.Task\LayerBase.Task.csproj"/>
        <ProjectReference Include="..\LayerBase.Generator\LayerBase.Generator\LayerBase.Generator.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false"/>

    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.0.0"/>
        <PackageReference Include="System.Text.Json" Version="8.0.6"/>
        <PackageReference Include="Arch.LowLevel" Version="1.1.5"/>
        <PackageReference Include="Collections.Pooled" Version="2.0.0-preview.27"/>
        <PackageReference Include="CommunityToolkit.HighPerformance" Version="8.2.2"/>
        <PackageReference Include="ZeroAllocJobScheduler" Version="1.1.2"/>
        <PackageReference Include="Microsoft.Extensions.ObjectPool" Version="7.0.0"/>
    </ItemGroup>

</Project>
