using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace LayerBase.Generator;

[Generator(LanguageNames.CSharp)]
public sealed class AssemblyModuleGenerator : IIncrementalGenerator
{
    private const string AssemblyModuleAttributeName = "LayerBase.Modules.AssemblyModuleAttribute";
    private const string ModuleServiceAttributeName = "LayerBase.Modules.ModuleServiceAttribute";

    private static readonly SymbolDisplayFormat FullyQualifiedTypeFormat =
        SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(
            SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var modules = context.SyntaxProvider
                             .ForAttributeWithMetadataName(
                                 AssemblyModuleAttributeName,
                                 static (node, _) => node is ClassDeclarationSyntax,
                                 static (ctx, _) => CreateModule(ctx))
                             .Where(static module => module is not null)
                             .Select(static (module, _) => module!);

        context.RegisterSourceOutput(modules, static (spc, module) => GenerateModule(spc, module));
    }

    private static ModuleInfo? CreateModule(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetSymbol is not INamedTypeSymbol typeSymbol)
        {
            return null;
        }

        var moduleAttribute = context.Attributes.FirstOrDefault(static attribute =>
            IsAttribute(attribute, AssemblyModuleAttributeName));

        if (moduleAttribute == null)
        {
            return null;
        }

        var moduleId = ReadStringArgument(moduleAttribute, 0);
        if (string.IsNullOrWhiteSpace(moduleId))
        {
            moduleId = typeSymbol.ToDisplayString(SymbolDisplayFormat.CSharpErrorMessageFormat);
        }

        var services = typeSymbol.GetAttributes()
                                 .Where(static attribute => IsAttribute(attribute, ModuleServiceAttributeName))
                                 .Select(ReadServiceContribution)
                                 .Where(static service => service is not null)
                                 .Select(static service => service!)
                                 .ToImmutableArray();

        return new ModuleInfo(
            typeSymbol.Name,
            typeSymbol.ContainingNamespace.IsGlobalNamespace
                ? null
                : typeSymbol.ContainingNamespace.ToDisplayString(),
            GetAccessibility(typeSymbol),
            moduleId!,
            services);
    }

    private static ServiceContributionInfo? ReadServiceContribution(AttributeData attribute)
    {
        var args = attribute.ConstructorArguments;
        if (args.Length < 4 ||
            args[0].Value is not ITypeSymbol ownerLayerType ||
            args[1].Value is not ITypeSymbol ownerScopeType ||
            args[2].Value is not ITypeSymbol serviceType ||
            args[3].Value is not ITypeSymbol implementationType)
        {
            return null;
        }

        var lifetime = "global::LayerBase.DI.ServiceLifetime.Singleton";
        if (args.Length >= 5 && args[4].Value is int lifetimeValue)
        {
            lifetime = lifetimeValue switch
            {
                0 => "global::LayerBase.DI.ServiceLifetime.Singleton",
                1 => "global::LayerBase.DI.ServiceLifetime.Scoped",
                2 => "global::LayerBase.DI.ServiceLifetime.Transient",
                3 => "global::LayerBase.DI.ServiceLifetime.Instance",
                _ => $"(global::LayerBase.DI.ServiceLifetime){lifetimeValue}"
            };
        }

        return new ServiceContributionInfo(
            ToTypeName(ownerLayerType),
            ToTypeName(ownerScopeType),
            ToTypeName(serviceType),
            ToTypeName(implementationType),
            lifetime);
    }

    private static void GenerateModule(SourceProductionContext spc, ModuleInfo module)
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated/>");
        source.AppendLine("#nullable enable");

        if (!string.IsNullOrEmpty(module.Namespace))
        {
            source.Append("namespace ").Append(module.Namespace).AppendLine();
            source.AppendLine("{");
        }

        var indent = string.IsNullOrEmpty(module.Namespace) ? string.Empty : "    ";
        source.Append(indent).Append(module.Accessibility).Append(" partial class ").Append(module.TypeName)
              .AppendLine(" : global::LayerBase.Modules.IAssemblyModule");
        source.Append(indent).AppendLine("{");

        source.Append(indent).AppendLine("    private static readonly global::LayerBase.Modules.AssemblyModuleManifest __Manifest =");
        source.Append(indent).AppendLine("        new global::LayerBase.Modules.AssemblyModuleManifest(");
        source.Append(indent).Append("            new global::LayerBase.Modules.AssemblyModuleId(\"")
              .Append(Escape(module.ModuleId))
              .AppendLine("\"),");
        AppendServiceArray(source, indent, module.Services);
        source.Append(indent).AppendLine("            global::System.Array.Empty<global::LayerBase.Modules.ContextContribution>(),");
        source.Append(indent).AppendLine("            global::System.Array.Empty<global::LayerBase.Modules.LocalCallContribution>(),");
        source.Append(indent).AppendLine("            global::System.Array.Empty<global::LayerBase.Modules.LayerToolContribution>());");
        source.AppendLine();

        source.Append(indent).AppendLine("    public global::LayerBase.Modules.AssemblyModuleId Id => __Manifest.ModuleId;");
        source.AppendLine();
        source.Append(indent).AppendLine("    public global::LayerBase.Modules.AssemblyModuleManifest Manifest => __Manifest;");
        source.Append(indent).AppendLine("}");

        if (!string.IsNullOrEmpty(module.Namespace))
        {
            source.AppendLine("}");
        }

        spc.AddSource($"{SanitizeHintName(module.Namespace)}_{module.TypeName}.AssemblyModule.g.cs",
            SourceText.From(source.ToString(), Encoding.UTF8));
    }

    private static void AppendServiceArray(StringBuilder source, string indent, ImmutableArray<ServiceContributionInfo> services)
    {
        if (services.IsDefaultOrEmpty)
        {
            source.Append(indent).AppendLine("            global::System.Array.Empty<global::LayerBase.Modules.ServiceContribution>(),");
            return;
        }

        source.Append(indent).AppendLine("            new global::LayerBase.Modules.ServiceContribution[]");
        source.Append(indent).AppendLine("            {");

        foreach (var service in services)
        {
            source.Append(indent).AppendLine("                global::LayerBase.Modules.ServiceContribution.ForTypes(");
            source.Append(indent).Append("                    typeof(").Append(service.ServiceType).AppendLine("),");
            source.Append(indent).Append("                    typeof(").Append(service.ImplementationType).AppendLine("),");
            source.Append(indent).Append("                    typeof(").Append(service.OwnerLayerType).AppendLine("),");
            source.Append(indent).Append("                    typeof(").Append(service.OwnerScopeType).AppendLine("),");
            source.Append(indent).Append("                    ").Append(service.Lifetime).AppendLine("),");
        }

        source.Append(indent).AppendLine("            },");
    }

    private static bool IsAttribute(AttributeData attribute, string metadataName)
    {
        return string.Equals(attribute.AttributeClass?.ToDisplayString(), metadataName, StringComparison.Ordinal);
    }

    private static string? ReadStringArgument(AttributeData attribute, int index)
    {
        return attribute.ConstructorArguments.Length > index
            ? attribute.ConstructorArguments[index].Value as string
            : null;
    }

    private static string ToTypeName(ITypeSymbol symbol)
    {
        return symbol.ToDisplayString(FullyQualifiedTypeFormat);
    }

    private static string GetAccessibility(INamedTypeSymbol symbol)
    {
        return symbol.DeclaredAccessibility switch
        {
            Accessibility.Public => "public",
            Accessibility.Private => "private",
            Accessibility.Protected => "protected",
            Accessibility.Internal => "internal",
            Accessibility.ProtectedAndInternal => "private protected",
            Accessibility.ProtectedOrInternal => "protected internal",
            _ => "internal"
        };
    }

    private static string Escape(string value)
    {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }

    private static string SanitizeHintName(string? value)
    {
        if (string.IsNullOrEmpty(value))
        {
            return "Global";
        }

        var chars = value.Select(static ch => char.IsLetterOrDigit(ch) ? ch : '_').ToArray();
        return new string(chars);
    }

    private sealed class ModuleInfo
    {
        public ModuleInfo(
            string typeName,
            string? @namespace,
            string accessibility,
            string moduleId,
            ImmutableArray<ServiceContributionInfo> services)
        {
            TypeName = typeName;
            Namespace = @namespace;
            Accessibility = accessibility;
            ModuleId = moduleId;
            Services = services;
        }

        public string TypeName { get; }

        public string? Namespace { get; }

        public string Accessibility { get; }

        public string ModuleId { get; }

        public ImmutableArray<ServiceContributionInfo> Services { get; }
    }

    private sealed class ServiceContributionInfo
    {
        public ServiceContributionInfo(
            string ownerLayerType,
            string ownerScopeType,
            string serviceType,
            string implementationType,
            string lifetime)
        {
            OwnerLayerType = ownerLayerType;
            OwnerScopeType = ownerScopeType;
            ServiceType = serviceType;
            ImplementationType = implementationType;
            Lifetime = lifetime;
        }

        public string OwnerLayerType { get; }

        public string OwnerScopeType { get; }

        public string ServiceType { get; }

        public string ImplementationType { get; }

        public string Lifetime { get; }
    }
}
