using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace LayerBase.Generator;

[Generator(LanguageNames.CSharp)]
public sealed class CallUsageAnalyzer : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var invocations = context.SyntaxProvider.CreateSyntaxProvider(
                                     static (node, _) => node is InvocationExpressionSyntax,
                                     static (ctx,  _) => GetCallUsage(ctx))
                                 .Where(static m => m != null)!;

        var classGroups = invocations.Collect();

        context.RegisterSourceOutput(classGroups, static (spc, usages) => GenerateMetadata(spc, usages));
    }

    private static string? GetCallUsage(GeneratorSyntaxContext ctx)
    {
        var invocation = (InvocationExpressionSyntax)ctx.Node;
        var model = ctx.SemanticModel;

        var name = invocation.Expression.ToString();
        if (!name.Contains("CallAsync") && !name.Contains("Call")) return null;

        var symbolInfo = model.GetSymbolInfo(invocation);
        var methodSymbol = symbolInfo.Symbol as IMethodSymbol ??
                           symbolInfo.CandidateSymbols.OfType<IMethodSymbol>().FirstOrDefault();

        if (methodSymbol == null) return null;

        // Check if it's LayerRuntime.CallAsync or IScopeLocalCallHandler.Call
        var containingType = methodSymbol.ContainingType.ToDisplayString();
        if (containingType != "LayerBase.LayerRuntime" &&
            !methodSymbol.ContainingType.AllInterfaces.Any(i => i.ToDisplayString().Contains("IScopeLocalCallHandler")))
            return null;

        if (methodSymbol.IsGenericMethod && methodSymbol.TypeArguments.Length >= 2)
        {
            // To be safe, find the parameter named 'request'
            var reqParam =
                methodSymbol.Parameters.FirstOrDefault(p =>
                    p.Name.Equals("request", StringComparison.OrdinalIgnoreCase));
            if (reqParam?.Type.TypeKind == TypeKind.TypeParameter) return null;
            if (reqParam != null) return reqParam.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        }

        return null;
    }

    private static void GenerateMetadata(SourceProductionContext spc, ImmutableArray<string> usages)
    {
        if (usages.IsDefaultOrEmpty) return;

        var distinctUsages = usages.Distinct().ToList();

        // We need a way to inject these into the global metadata.
        // Since we can't easily find "which layer" is calling (it could be anyone),
        // we will emit a global initializer that adds these to a static list in LayerHub,
        // which GetTopologyMarkdown can then consume.

        // Wait, a better way: LayerHub can have a static HashSet<Type> of "GloballyInvokedCalls".

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using System;");
        sb.AppendLine("namespace LayerBase.Call");
        sb.AppendLine("{");
        sb.AppendLine("    internal static class CallUsageRegistry");
        sb.AppendLine("    {");
        sb.AppendLine("        [global::System.Runtime.CompilerServices.ModuleInitializer]");
        sb.AppendLine("        public static void Initialize()");
        sb.AppendLine("        {");
        foreach (var usage in distinctUsages)
            sb.AppendLine($"            global::LayerBase.Call.CallUsageTracker.RegisterUsed(typeof({usage}));");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource("CallUsageRegistry.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
