using System.Collections.Immutable;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace LayerBase.Generator;

[Generator(LanguageNames.CSharp)]
public sealed class FullSnapGenerator : IIncrementalGenerator
{
    private const string FullSnapMetadataName = "LayerBase.Snap.IFullSnap";
    private const string GeneratedNodeMetadataName = "LayerBase.Snap.IGeneratedFullSnapNode";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var candidates = context.SyntaxProvider.CreateSyntaxProvider(
                static (node, _) => node is ClassDeclarationSyntax classDeclaration &&
                                    classDeclaration.Modifiers.Any(SyntaxKind.PartialKeyword),
                static (ctx, _) => ctx.SemanticModel.GetDeclaredSymbol((ClassDeclarationSyntax)ctx.Node) as INamedTypeSymbol)
            .Where(static symbol => symbol != null)!;

        var compilationAndCandidates = context.CompilationProvider.Combine(candidates.Collect());

        context.RegisterSourceOutput(compilationAndCandidates, static (spc, source) =>
        {
            Execute(spc, source.Left, source.Right);
        });
    }

    private static void Execute(
        SourceProductionContext spc,
        Compilation compilation,
        ImmutableArray<INamedTypeSymbol?> candidates)
    {
        INamedTypeSymbol? fullSnapSymbol = compilation.GetTypeByMetadataName(FullSnapMetadataName);
        INamedTypeSymbol? generatedNodeSymbol = compilation.GetTypeByMetadataName(GeneratedNodeMetadataName);

        if (fullSnapSymbol == null || generatedNodeSymbol == null)
        {
            return;
        }

        foreach (INamedTypeSymbol symbol in candidates.Distinct(SymbolEqualityComparer.Default).OfType<INamedTypeSymbol>())
        {
            if (symbol.TypeKind != TypeKind.Class ||
                !IsPartialChain(symbol) ||
                !ImplementsInterface(symbol, fullSnapSymbol) ||
                ImplementsInterface(symbol, generatedNodeSymbol))
            {
                continue;
            }

            string source = GeneratePartial(symbol);
            if (source.Length == 0)
            {
                continue;
            }

            spc.AddSource(CreateHintName(symbol), SourceText.From(source, Encoding.UTF8));
        }
    }

    private static bool ImplementsInterface(INamedTypeSymbol symbol, INamedTypeSymbol interfaceSymbol)
    {
        return symbol.AllInterfaces.Any(i =>
            SymbolEqualityComparer.Default.Equals(i, interfaceSymbol) ||
            SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, interfaceSymbol));
    }

    private static bool IsPartial(INamedTypeSymbol type)
    {
        foreach (SyntaxReference syntaxRef in type.DeclaringSyntaxReferences)
        {
            if (syntaxRef.GetSyntax() is TypeDeclarationSyntax typeDeclaration &&
                typeDeclaration.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword)))
            {
                return true;
            }
        }

        return false;
    }

    private static bool IsPartialChain(INamedTypeSymbol type)
    {
        for (INamedTypeSymbol? current = type; current != null; current = current.ContainingType)
        {
            if (!IsPartial(current))
            {
                return false;
            }
        }

        return true;
    }

    private static string GeneratePartial(INamedTypeSymbol symbol)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("// This file was generated by FullSnapGenerator.");

        string? ns = symbol.ContainingNamespace is { IsGlobalNamespace: false } namespaceSymbol
            ? namespaceSymbol.ToDisplayString()
            : null;

        if (!string.IsNullOrEmpty(ns))
        {
            builder.Append("namespace ").Append(ns).AppendLine();
            builder.AppendLine("{");
        }

        var containingTypes = new Stack<INamedTypeSymbol>();
        for (INamedTypeSymbol? current = symbol; current != null; current = current.ContainingType)
        {
            containingTypes.Push(current);
        }

        string indent = string.Empty;

        while (containingTypes.Count > 0)
        {
            INamedTypeSymbol current = containingTypes.Pop();
            builder.Append(indent)
                .Append("partial class ")
                .Append(current.Name);

            AppendTypeParameters(builder, current);

            if (SymbolEqualityComparer.Default.Equals(current, symbol))
            {
                builder.Append(" : global::LayerBase.Snap.IGeneratedFullSnapNode");
            }

            builder.AppendLine();
            builder.Append(indent).AppendLine("{");
            indent += "    ";
        }

        builder.Append(indent)
            .Append("string global::LayerBase.Snap.IGeneratedFullSnapNode.__SnapKey => \"")
            .Append(EscapeString(BuildSnapKey(symbol)))
            .AppendLine("\";");
        builder.Append(indent)
            .AppendLine("int global::LayerBase.Snap.IGeneratedFullSnapNode.__SnapVersion => 1;");

        for (int i = 0, count = GetContainingTypeDepth(symbol) + 1; i < count; i++)
        {
            indent = indent.Substring(0, indent.Length - 4);
            builder.Append(indent).AppendLine("}");
        }

        if (!string.IsNullOrEmpty(ns))
        {
            builder.AppendLine("}");
        }

        return builder.ToString();
    }

    private static void AppendTypeParameters(StringBuilder builder, INamedTypeSymbol symbol)
    {
        if (symbol.TypeParameters.Length == 0)
        {
            return;
        }

        builder.Append('<');

        for (int i = 0; i < symbol.TypeParameters.Length; i++)
        {
            if (i > 0)
            {
                builder.Append(", ");
            }

            builder.Append(symbol.TypeParameters[i].Name);
        }

        builder.Append('>');
    }

    private static int GetContainingTypeDepth(INamedTypeSymbol symbol)
    {
        int depth = 0;
        for (INamedTypeSymbol? current = symbol.ContainingType; current != null; current = current.ContainingType)
        {
            depth++;
        }

        return depth;
    }

    private static string BuildSnapKey(INamedTypeSymbol symbol)
    {
        var parts = new Stack<string>();

        for (INamedTypeSymbol? current = symbol; current != null; current = current.ContainingType)
        {
            parts.Push(current.Name);
        }

        string typePath = string.Join(".", parts);
        string? ns = symbol.ContainingNamespace is { IsGlobalNamespace: false } namespaceSymbol
            ? namespaceSymbol.ToDisplayString()
            : null;

        return string.IsNullOrEmpty(ns)
            ? $"{typePath}_FullSnap"
            : $"{ns}.{typePath}_FullSnap";
    }

    private static string CreateHintName(INamedTypeSymbol symbol)
    {
        string display = symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        return $"{Sanitize(display)}.FullSnap.g.cs";
    }

    private static string Sanitize(string value)
    {
        var builder = new StringBuilder(value.Length);
        foreach (char ch in value)
        {
            builder.Append(char.IsLetterOrDigit(ch) ? ch : '_');
        }

        return builder.ToString();
    }

    private static string EscapeString(string value)
    {
        return value.Replace("\\", "\\\\").Replace("\"", "\\\"");
    }
}
