using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace LayerBase.Generator;

[Generator(LanguageNames.CSharp)]
public sealed class LayerServiceGenerator : IIncrementalGenerator
{
    private const string OwnerLayerAttributeName = "LayerBase.Layers.OwnerLayerAttribute";
    private const string IServiceMetadataName = "LayerBase.DI.IService";
    private const string LayerMetadataName = "LayerBase.Layers.Layer";
    private const string EventHandlerMetadataName = "LayerBase.Core.EventHandler.IEventHandler`1";
    private const string EventHandlerAsyncMetadataName = "LayerBase.Core.EventHandler.IEventHandlerAsync`1";
    private const string CallHandlerMetadataName = "LayerBase.Call.ILayerCallHandler`2";

    private static readonly string OwnerLayerAttributeSource = @"// <auto-generated />
using System;

namespace LayerBase.Layers
{
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = true, Inherited = false)]
    public sealed class OwnerLayerAttribute : Attribute
    {
        public OwnerLayerAttribute(Type layerType)
        {
            LayerType = layerType ?? throw new ArgumentNullException(nameof(layerType));
        }

        public Type LayerType { get; }
    }
}
";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(static ctx =>
        {
            ctx.AddSource("OwnerLayerAttribute.g.cs", SourceText.From(OwnerLayerAttributeSource, Encoding.UTF8));
        });

        var registrations = context.SyntaxProvider
                                   .ForAttributeWithMetadataName(
                                       OwnerLayerAttributeName,
                                       static (node, _) => node is ClassDeclarationSyntax,
                                       static (ctx,  ct) => CreateRegistrations(ctx))
                                   .SelectMany(static (items, _) => items);

        var compilationAndRegistrations = context.CompilationProvider.Combine(registrations.Collect());

        context.RegisterSourceOutput(compilationAndRegistrations, static (spc, source) =>
        {
            var compilation = source.Left;
            var collected = source.Right;

            var iServiceSymbol = compilation.GetTypeByMetadataName(IServiceMetadataName);
            var layerSymbol = compilation.GetTypeByMetadataName(LayerMetadataName);
            var eventHandlerSymbol = compilation.GetTypeByMetadataName(EventHandlerMetadataName);
            var eventHandlerAsyncSymbol = compilation.GetTypeByMetadataName(EventHandlerAsyncMetadataName);
            var callHandlerSymbol = compilation.GetTypeByMetadataName(CallHandlerMetadataName);

            if (iServiceSymbol == null || layerSymbol == null) return;

            var validRegistrations = new List<ServiceRegistration>();
            var callHandlerRegistrations = new List<CallHandlerRegistration>();
            foreach (var registration in collected)
            {
                var serviceSymbol = registration.ServiceType;
                var targetLayer = registration.LayerType;
                var implementsService = ImplementsInterface(serviceSymbol, iServiceSymbol);
                var implementsEventHandler = ImplementsInterface(serviceSymbol, eventHandlerSymbol) ||
                                             ImplementsInterface(serviceSymbol, eventHandlerAsyncSymbol) ||
                                             ImplementsInterfaceByMetadataName(serviceSymbol, EventHandlerMetadataName) ||
                                             ImplementsInterfaceByMetadataName(serviceSymbol, EventHandlerAsyncMetadataName);
                var implementsCallHandler = ImplementsInterface(serviceSymbol, callHandlerSymbol) ||
                                            ImplementsInterfaceByMetadataName(serviceSymbol, CallHandlerMetadataName);

                if (!implementsService)
                {
                    if (implementsCallHandler)
                    {
                        foreach (var impl in GetCallHandlerInterfaces(serviceSymbol, callHandlerSymbol))
                        {
                            callHandlerRegistrations.Add(new CallHandlerRegistration(
                                serviceSymbol,
                                targetLayer,
                                impl.RequestType,
                                impl.ResponseType,
                                registration.Location ?? serviceSymbol.Locations.FirstOrDefault()));
                        }

                        continue;
                    }

                    if (implementsEventHandler) continue;

                    spc.ReportDiagnostic(Diagnostic.Create(Diagnostics.ServiceMustImplementIService,
                        registration.Location ?? serviceSymbol.Locations.FirstOrDefault(),
                        serviceSymbol.ToDisplayString()));
                    continue;
                }

                if (!InheritsFromLayer(targetLayer, layerSymbol))
                {
                    spc.ReportDiagnostic(Diagnostic.Create(Diagnostics.LayerMustInheritLayer,
                        registration.Location ?? targetLayer.Locations.FirstOrDefault(),
                        targetLayer.ToDisplayString()));
                    continue;
                }

                if (!IsPartial(targetLayer))
                {
                    spc.ReportDiagnostic(Diagnostic.Create(Diagnostics.LayerMustBePartial,
                        registration.Location ?? targetLayer.Locations.FirstOrDefault(),
                        targetLayer.ToDisplayString()));
                    continue;
                }

                if (!HasAccessibleParameterlessConstructor(serviceSymbol))
                {
                    spc.ReportDiagnostic(Diagnostic.Create(Diagnostics.ServiceNeedsPublicParameterlessConstructor,
                        registration.Location ?? serviceSymbol.Locations.FirstOrDefault(),
                        serviceSymbol.ToDisplayString()));
                    continue;
                }

                if (serviceSymbol.IsAbstract)
                {
                    spc.ReportDiagnostic(Diagnostic.Create(Diagnostics.ServiceCannotBeAbstract,
                        registration.Location ?? serviceSymbol.Locations.FirstOrDefault(),
                        serviceSymbol.ToDisplayString()));
                    continue;
                }

                validRegistrations.Add(registration);
            }

            var conflictingRequests = callHandlerRegistrations
                .GroupBy(static binding => binding.RequestType, SymbolEqualityComparer.Default)
                .Select(static group => new
                {
                    RequestType = group.Key,
                    Count = group.Count(),
                    Bindings = group.Select(static binding => new CallBindingSignature(binding.LayerType, binding.ResponseType))
                        .Distinct(CallBindingSignatureComparer.Instance)
                        .OrderBy(static binding => binding.LayerType.ToDisplayString())
                        .ThenBy(static binding => binding.ResponseType.ToDisplayString())
                        .ToList()
                })
                .Where(static entry => entry.Count > 1)
                .ToDictionary(static entry => entry.RequestType, static entry => entry.Bindings, SymbolEqualityComparer.Default);

            foreach (var registration in callHandlerRegistrations)
            {
                if (!conflictingRequests.TryGetValue(registration.RequestType, out var bindings)) continue;

                var bindingList = string.Join(", ", bindings.Select(static binding =>
                    $"{binding.LayerType.ToDisplayString()} -> {binding.ResponseType.ToDisplayString()}"));

                spc.ReportDiagnostic(Diagnostic.Create(
                    Diagnostics.RequestMustHaveSingleBinding,
                    registration.Location ?? registration.ServiceType.Locations.FirstOrDefault(),
                    registration.RequestType.ToDisplayString(),
                    bindingList));
            }

            var groupedByLayer = validRegistrations
                .GroupBy(r => r.LayerType, SymbolEqualityComparer.Default);

            foreach (var group in groupedByLayer)
            {
                if (group.Key is not INamedTypeSymbol layerKey) continue;

                var sourceText = GenerateLayerPartial(layerKey, group);
                if (string.IsNullOrEmpty(sourceText)) continue;
                spc.AddSource(CreateHintName(layerKey), SourceText.From(sourceText, Encoding.UTF8));
            }
        });
    }

    private static ImmutableArray<ServiceRegistration> CreateRegistrations(GeneratorAttributeSyntaxContext context)
    {
        var serviceSymbol = (INamedTypeSymbol)context.TargetSymbol;
        var builder = ImmutableArray.CreateBuilder<ServiceRegistration>();

        foreach (var attribute in context.Attributes)
        {
            if (attribute.ConstructorArguments.Length != 1) continue;

            if (attribute.ConstructorArguments[0].Value is not INamedTypeSymbol layerSymbol) continue;

            var location = attribute.ApplicationSyntaxReference?.GetSyntax()?.GetLocation();
            builder.Add(new ServiceRegistration(serviceSymbol, layerSymbol, location));
        }

        return builder.ToImmutable();
    }

    private static bool ImplementsInterface(INamedTypeSymbol type, INamedTypeSymbol? interfaceSymbol)
    {
        if (interfaceSymbol == null) return false;

        return type.AllInterfaces.Any(i =>
            SymbolEqualityComparer.Default.Equals(i, interfaceSymbol) ||
            SymbolEqualityComparer.Default.Equals(i.OriginalDefinition, interfaceSymbol));
    }

    private static bool ImplementsInterfaceByMetadataName(INamedTypeSymbol type, string metadataName)
    {
        if (string.IsNullOrWhiteSpace(metadataName)) return false;

        return type.AllInterfaces.Any(i =>
        {
            var candidate = i.OriginalDefinition is INamedTypeSymbol named ? named : i;
            var display = candidate.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            return display switch
            {
                "global::LayerBase.Call.ILayerCallHandler<TRequest, TResponse>" when
                    metadataName == CallHandlerMetadataName => true,
                "global::LayerBase.Core.EventHandler.IEventHandler<TValue>" when
                    metadataName == EventHandlerMetadataName => true,
                "global::LayerBase.Core.EventHandler.IEventHandlerAsync<TValue>" when
                    metadataName == EventHandlerAsyncMetadataName => true,
                _ => false
            };
        });
    }

    private static IEnumerable<CallHandlerImplementation> GetCallHandlerInterfaces(INamedTypeSymbol handlerType,
                                                                                   INamedTypeSymbol? callHandlerSymbol)
    {
        if (callHandlerSymbol == null) yield break;

        foreach (var iface in handlerType.AllInterfaces.OfType<INamedTypeSymbol>())
        {
            if (!SymbolEqualityComparer.Default.Equals(iface.OriginalDefinition, callHandlerSymbol)) continue;
            if (iface.TypeArguments.Length != 2) continue;

            yield return new CallHandlerImplementation(iface.TypeArguments[0], iface.TypeArguments[1]);
        }
    }

    private static bool InheritsFromLayer(INamedTypeSymbol target, INamedTypeSymbol layerSymbol)
    {
        for (var current = target; current != null; current = current.BaseType)
            if (SymbolEqualityComparer.Default.Equals(current, layerSymbol))
                return true;

        return false;
    }

    private static bool IsPartial(INamedTypeSymbol type)
    {
        foreach (var reference in type.DeclaringSyntaxReferences)
            if (reference.GetSyntax() is TypeDeclarationSyntax typeDeclaration &&
                typeDeclaration.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword)))
                return true;

        return false;
    }

    private static bool HasAccessibleParameterlessConstructor(INamedTypeSymbol type)
    {
        foreach (var ctor in type.InstanceConstructors)
        {
            if (ctor.Parameters.Length != 0 || ctor.IsStatic) continue;

            if (ctor.DeclaredAccessibility is Accessibility.Public or Accessibility.Internal
                or Accessibility.ProtectedOrInternal) return true;
        }

        return false;
    }

    private static string GenerateLayerPartial(INamedTypeSymbol                 layerType,
                                               IEnumerable<ServiceRegistration> registrations)
    {
        var services = (registrations ?? Enumerable.Empty<ServiceRegistration>())
                       .Where(r => r?.ServiceType != null)
                       .Select(r => r.ServiceType!)
                       .Distinct<INamedTypeSymbol>(SymbolEqualityComparer.Default)
                       .OrderBy(s => s.ToDisplayString())
                       .ToList();

        if (services.Count == 0) return string.Empty;

        var layerDisplayName = layerType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var layerIdentifier = layerType.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat);
        var namespaceSymbol = layerType.ContainingNamespace;
        var @namespace = namespaceSymbol is { IsGlobalNamespace: false }
            ? namespaceSymbol.ToDisplayString()
            : null;

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("// This file was generated by LayerServiceGenerator.");
        builder.AppendLine("using LayerBase.Layers;");

        if (!string.IsNullOrEmpty(@namespace))
        {
            builder.Append("namespace ").Append(@namespace).AppendLine();
            builder.AppendLine("{");
        }

        builder.Append("partial class ").Append(layerIdentifier).AppendLine();
        builder.AppendLine("{");
        builder.Append("    static ").Append(layerType.Name).AppendLine("()");
        builder.AppendLine("    {");
        builder.Append("        LayerServiceRegistry.Register(typeof(").Append(layerDisplayName)
               .AppendLine("), static layerInstance =>");
        builder.AppendLine("        {");
        builder.Append("            var typedLayer = (").Append(layerDisplayName).AppendLine(")layerInstance;");

        foreach (var service in services)
        {
            var serviceDisplay = service.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            builder.Append("            typedLayer.RegisterService(new ").Append(serviceDisplay).AppendLine("());");
        }

        builder.AppendLine("        });");
        builder.AppendLine("    }");
        builder.AppendLine("}");

        if (!string.IsNullOrEmpty(@namespace)) builder.AppendLine("}");

        return builder.ToString();
    }

    private static string CreateHintName(INamedTypeSymbol layerType)
    {
        var name = layerType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var sanitized = new StringBuilder(name.Length);
        foreach (var ch in name) sanitized.Append(char.IsLetterOrDigit(ch) ? ch : '_');
        return $"{sanitized}.LayerServices.g.cs";
    }

#pragma warning disable RS2008 // Enable analyzer release tracking
    private static class Diagnostics
    {
        private const string Category = "LayerServiceGenerator";

        public static readonly DiagnosticDescriptor ServiceMustImplementIService =
            new(
                "LBG001",
                "Service must implement IService",
                "Type '{0}' is marked with OwnerLayer but does not implement LayerBase.DI.IService",
                Category,
                DiagnosticSeverity.Error,
                true);

        public static readonly DiagnosticDescriptor LayerMustInheritLayer =
            new(
                "LBG002",
                "OwnerLayer target must derive from Layer",
                "Type '{0}' is not a Layer and cannot be used with OwnerLayerAttribute",
                Category,
                DiagnosticSeverity.Error,
                true);

        public static readonly DiagnosticDescriptor LayerMustBePartial =
            new(
                "LBG003",
                "Layer must be partial",
                "Layer '{0}' must be declared as partial to allow generator to emit registrations",
                Category,
                DiagnosticSeverity.Error,
                true);

        public static readonly DiagnosticDescriptor ServiceNeedsPublicParameterlessConstructor =
            new(
                "LBG004",
                "Service needs parameterless constructor",
                "Service '{0}' must have a public or internal parameterless constructor",
                Category,
                DiagnosticSeverity.Error,
                true);

        public static readonly DiagnosticDescriptor ServiceCannotBeAbstract =
            new(
                "LBG005",
                "Service cannot be abstract",
                "Service '{0}' cannot be abstract when used with OwnerLayerAttribute",
                Category,
                DiagnosticSeverity.Error,
                true);

        public static readonly DiagnosticDescriptor RequestMustHaveSingleBinding =
            new(
                "LBG006",
                "Call request must map to exactly one target and one response",
                "Call request '{0}' has multiple call bindings: {1}. Call is only for single-target functional slices, so each request must map to exactly one layer and one response.",
                Category,
                DiagnosticSeverity.Error,
                true);
    }
#pragma warning restore RS2008

    private sealed class ServiceRegistration
    {
        public ServiceRegistration(INamedTypeSymbol serviceType, INamedTypeSymbol layerType, Location? location)
        {
            ServiceType = serviceType;
            LayerType = layerType;
            Location = location;
        }

        public INamedTypeSymbol ServiceType { get; }

        public INamedTypeSymbol LayerType { get; }

        public Location? Location { get; }
    }

    private sealed class CallHandlerRegistration
    {
        public CallHandlerRegistration(INamedTypeSymbol serviceType, INamedTypeSymbol layerType, ITypeSymbol requestType,
                                       ITypeSymbol responseType, Location? location)
        {
            ServiceType = serviceType;
            LayerType = layerType;
            RequestType = requestType;
            ResponseType = responseType;
            Location = location;
        }

        public INamedTypeSymbol ServiceType { get; }
        public INamedTypeSymbol LayerType { get; }
        public ITypeSymbol RequestType { get; }
        public ITypeSymbol ResponseType { get; }
        public Location? Location { get; }
    }

    private readonly record struct CallHandlerImplementation(ITypeSymbol RequestType, ITypeSymbol ResponseType);

    private readonly record struct CallBindingSignature(INamedTypeSymbol LayerType, ITypeSymbol ResponseType);

    private sealed class CallBindingSignatureComparer : IEqualityComparer<CallBindingSignature>
    {
        public static readonly CallBindingSignatureComparer Instance = new();

        public bool Equals(CallBindingSignature x, CallBindingSignature y)
        {
            return SymbolEqualityComparer.Default.Equals(x.LayerType, y.LayerType)
                   && SymbolEqualityComparer.Default.Equals(x.ResponseType, y.ResponseType);
        }

        public int GetHashCode(CallBindingSignature obj)
        {
            var hash = SymbolEqualityComparer.Default.GetHashCode(obj.LayerType);
            hash = (hash * 397) ^ SymbolEqualityComparer.Default.GetHashCode(obj.ResponseType);
            return hash;
        }
    }
}
