<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <IsPackable>true</IsPackable>
        <Nullable>enable</Nullable>
        <LangVersion>12</LangVersion>
        <IncludeBuildOutput>false</IncludeBuildOutput>
        <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
        <IsRoslynComponent>true</IsRoslynComponent>

        <RootNamespace>LayerBase.Generator</RootNamespace>
        <PackageId>LayerBase.Generator</PackageId>
        <GeneratePackageOnBuild Condition="'$(GITHUB_ACTIONS)' != 'true'">true</GeneratePackageOnBuild>
        <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
        <Title>LayerBase.Generator</Title>
        <Authors>扭矩不足</Authors>
        <Description>分层式DI依赖注入框架,附加层级式事件总线与异步事件总线支持</Description>
        <PackageProjectUrl>https://github.com/avaw23112/LayerBase.git</PackageProjectUrl>
        <PackageLicenseUrl>https://github.com/avaw23112/LayerBase</PackageLicenseUrl>
        <RepositoryUrl>https://github.com/avaw23112/LayerBase.git</RepositoryUrl>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <Version>1.4.7.3</Version>
        <PackageOutputPath>$(MSBuildProjectDirectory)/../../nupkgs</PackageOutputPath>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\README.md" Pack="true" PackagePath="\"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="3.3.4">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.3.0"/>
        <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.3.0"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Remove="SourceGeneratorWithAdditionalFiles.cs"/>
        <Compile Remove="SourceGeneratorWithAttributes.cs"/>
    </ItemGroup>
    <ItemGroup>
        <None Include="$(TargetDir)$(AssemblyName).dll"
              Pack="true"
              PackagePath="analyzers/dotnet/cs"
              Visible="false" />
        <None Include="$(TargetDir)$(AssemblyName).pdb"
              Pack="true"
              PackagePath="analyzers/dotnet/cs"
              Visible="false"
              Condition="Exists('$(TargetDir)$(AssemblyName).pdb')"/>
    </ItemGroup>


</Project>
