using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace LayerBase.Generator;

[Generator(LanguageNames.CSharp)]
public sealed class ProjectedActorTypeGenerator : IIncrementalGenerator
{
    private const string PooledActorName = "LayerBase.Actor.IPooledActor";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var pooledActors = context.CompilationProvider.Select(
            static (compilation, _) => CollectProjectedActors(compilation));

        context.RegisterSourceOutput(
            pooledActors,
            static (spc, actors) =>
            {
                if (actors.IsDefault)
                {
                    return;
                }

                string source = GenerateSource(actors);
                if (!string.IsNullOrEmpty(source))
                {
                    spc.AddSource(
                        "GeneratedProjectedActorTypes.g.cs",
                        SourceText.From(source, Encoding.UTF8));
                }
            });
    }

    private static ImmutableArray<INamedTypeSymbol> CollectProjectedActors(
        Compilation compilation)
    {
        if (!string.Equals(
                compilation.AssemblyName,
                "LayerBase",
                System.StringComparison.Ordinal))
        {
            return default;
        }

        INamedTypeSymbol? pooledActor = compilation.GetTypeByMetadataName(PooledActorName);
        if (pooledActor == null)
        {
            return ImmutableArray<INamedTypeSymbol>.Empty;
        }

        var builder = ImmutableArray.CreateBuilder<INamedTypeSymbol>();

        void VisitNamespace(INamespaceSymbol ns)
        {
            foreach (INamespaceSymbol childNs in ns.GetNamespaceMembers())
            {
                VisitNamespace(childNs);
            }

            foreach (INamedTypeSymbol type in ns.GetTypeMembers())
            {
                VisitType(type);
            }
        }

        void VisitType(INamedTypeSymbol type)
        {
            foreach (INamedTypeSymbol child in type.GetTypeMembers())
            {
                VisitType(child);
            }

            if (type.TypeKind != TypeKind.Class
                || type.IsAbstract
                || type.IsGenericType)
            {
                return;
            }

            if (!type.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, pooledActor)))
            {
                return;
            }

            if (!HasAccessibleParameterlessConstructor(type))
            {
                return;
            }

            builder.Add(type);
        }

        VisitNamespace(compilation.Assembly.GlobalNamespace);

        return builder
            .ToImmutable()
            .Distinct(SymbolEqualityComparer.Default)
            .Cast<INamedTypeSymbol>()
            .OrderBy(static type => type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
            .ToImmutableArray();
    }

    private static bool HasAccessibleParameterlessConstructor(
        INamedTypeSymbol type)
    {
        foreach (IMethodSymbol ctor in type.InstanceConstructors)
        {
            if (ctor.Parameters.Length != 0 || ctor.IsStatic)
            {
                continue;
            }

            if (ctor.DeclaredAccessibility is Accessibility.Public
                or Accessibility.Internal
                or Accessibility.ProtectedOrInternal)
            {
                return true;
            }
        }

        return false;
    }

    private static string GenerateSource(
        ImmutableArray<INamedTypeSymbol> actors)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("using System;");
        builder.AppendLine("using LayerBase.Actor;");
        builder.AppendLine();
        builder.AppendLine("namespace LayerBase.ECS.Projection.Generated;");
        builder.AppendLine();
        builder.AppendLine("internal static partial class GeneratedProjectedActorTypes");
        builder.AppendLine("{");

        for (int i = 0; i < actors.Length; i++)
        {
            builder.Append("    public const int ")
                .Append(GetConstantName(actors[i]))
                .Append(" = ")
                .Append(i)
                .AppendLine(";");
        }

        if (actors.Length > 0)
        {
            builder.AppendLine();
        }

        builder.AppendLine("    private static partial void RegisterGeneratedTypes(");
        builder.AppendLine("        ProjectedActorTypeRegistry registry)");
        builder.AppendLine("    {");

        foreach (INamedTypeSymbol actor in actors)
        {
            string display = actor.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            builder.Append("        registry.RegisterGenerated(").AppendLine();
            builder.Append("            actorTypeId: ").Append(GetConstantName(actor)).AppendLine(",");
            builder.Append("            actorType: typeof(").Append(display).AppendLine("),");
            builder.Append("            factory: static actorWorld =>").AppendLine();
            builder.Append("                actorWorld.CreateProjectedActor<").Append(display).AppendLine(">());");
        }

        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    private static partial void TryWriteGeneratedId<TActor>(");
        builder.AppendLine("        ref int actorTypeId)");
        builder.AppendLine("        where TActor : class, IPooledActor, new()");
        builder.AppendLine("    {");
        builder.AppendLine("        Type type = typeof(TActor);");

        foreach (INamedTypeSymbol actor in actors)
        {
            string display = actor.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            builder.Append("        if (type == typeof(").Append(display).AppendLine("))");
            builder.AppendLine("        {");
            builder.Append("            actorTypeId = ").Append(GetConstantName(actor)).AppendLine(";");
            builder.AppendLine("            return;");
            builder.AppendLine("        }");
        }
        builder.AppendLine("    }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string GetConstantName(
        INamedTypeSymbol actor)
    {
        var builder = new StringBuilder();
        foreach (char ch in actor.ToDisplayString(SymbolDisplayFormat.MinimallyQualifiedFormat))
        {
            builder.Append(char.IsLetterOrDigit(ch) ? ch : '_');
        }

        if (builder.Length == 0 || !char.IsLetter(builder[0]))
        {
            builder.Insert(0, 'T');
        }

        return builder.ToString();
    }
}
