using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace LayerBase.Generator;

[Generator(LanguageNames.CSharp)]
public sealed class ScopeRefPostGenerator : IIncrementalGenerator
{
    private const string ScopeEventAttributeName = "LayerBase.Scope.ScopeEventAttribute`1";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var events = context.SyntaxProvider
                            .ForAttributeWithMetadataName(
                                ScopeEventAttributeName,
                                static (_, _) => true,
                                static (ctx, _) => GetScopeEvent(ctx))
                            .Where(static item => item != null)!;

        context.RegisterSourceOutput(events.Collect(), static (spc, items) => Generate(spc, items));
    }

    private static ScopeEventInfo? GetScopeEvent(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetSymbol is not INamedTypeSymbol eventType)
        {
            return null;
        }

        AttributeData? attribute = context.Attributes.FirstOrDefault(static attr =>
            attr.AttributeClass?.OriginalDefinition.ToDisplayString() ==
            "LayerBase.Scope.ScopeEventAttribute<TScope>");

        INamedTypeSymbol? scopeType = attribute?.AttributeClass?.TypeArguments.FirstOrDefault() as INamedTypeSymbol;
        if (scopeType == null)
        {
            return null;
        }

        return new ScopeEventInfo(
            eventType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            scopeType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
    }

    private static void Generate(SourceProductionContext spc, ImmutableArray<ScopeEventInfo?> nullableItems)
    {
        var items = nullableItems
                    .Where(static item => item != null)
                    .Select(static item => item!)
                    .OrderBy(static item => item.ScopeType, StringComparer.Ordinal)
                    .ThenBy(static item => item.EventType, StringComparer.Ordinal)
                    .ToImmutableArray();

        if (items.Length == 0)
        {
            return;
        }

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("namespace LayerBase.Scope");
        builder.AppendLine("{");
        builder.AppendLine("    public static class ScopeRefPostExtensions");
        builder.AppendLine("    {");

        for (int i = 0; i < items.Length; i++)
        {
            ScopeEventInfo item = items[i];

            builder.AppendLine(
                $"        public static bool Post(this global::LayerBase.Scope.ScopeRef<{item.ScopeType}> scope, {item.EventType} message)");
            builder.AppendLine("        {");
            builder.AppendLine("            return scope.TryPost(message);");
            builder.AppendLine("        }");

            if (i + 1 < items.Length)
            {
                builder.AppendLine();
            }
        }

        builder.AppendLine("    }");
        builder.AppendLine("}");

        spc.AddSource("LayerBase.Scope.ScopeRefPostExtensions.g.cs", builder.ToString());
    }

    private sealed record ScopeEventInfo(string EventType, string ScopeType);
}
