using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace LayerBase.Generator;

[Generator(LanguageNames.CSharp)]
public sealed class ScopeRefCallGenerator : IIncrementalGenerator
{
    private const string ScopeCallAttributeName = "LayerBase.Scope.ScopeCallAttribute`2";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var calls = context.SyntaxProvider
                           .ForAttributeWithMetadataName(
                               ScopeCallAttributeName,
                               static (_, _) => true,
                               static (ctx, _) => GetScopeCall(ctx))
                           .Where(static item => item != null)!;

        context.RegisterSourceOutput(calls.Collect(), static (spc, items) => Generate(spc, items));
    }

    private static ScopeCallInfo? GetScopeCall(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetSymbol is not INamedTypeSymbol requestType)
        {
            return null;
        }

        AttributeData? attribute = context.Attributes.FirstOrDefault(static attr =>
            attr.AttributeClass?.OriginalDefinition.ToDisplayString() ==
            "LayerBase.Scope.ScopeCallAttribute<TScope, TResult>");

        if (attribute?.AttributeClass == null || attribute.AttributeClass.TypeArguments.Length < 2)
        {
            return null;
        }

        var scopeType = attribute.AttributeClass.TypeArguments[0] as INamedTypeSymbol;
        var resultType = attribute.AttributeClass.TypeArguments[1];
        if (scopeType == null || resultType == null)
        {
            return null;
        }

        return new ScopeCallInfo(
            requestType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            scopeType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            resultType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
    }

    private static void Generate(SourceProductionContext spc, ImmutableArray<ScopeCallInfo?> nullableItems)
    {
        var items = nullableItems
                    .Where(static item => item != null)
                    .Select(static item => item!)
                    .OrderBy(static item => item.ScopeType, StringComparer.Ordinal)
                    .ThenBy(static item => item.RequestType, StringComparer.Ordinal)
                    .ToImmutableArray();

        if (items.Length == 0)
        {
            return;
        }

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine("namespace LayerBase.Scope");
        builder.AppendLine("{");
        builder.AppendLine("    public static class ScopeRefCallExtensions");
        builder.AppendLine("    {");

        var callIds = items
                      .Select(static item => item.RequestType)
                      .Distinct(StringComparer.Ordinal)
                      .OrderBy(static item => item, StringComparer.Ordinal)
                      .Select(static (requestType, index) => (RequestType: requestType, CallId: index))
                      .ToDictionary(static item => item.RequestType, static item => item.CallId, StringComparer.Ordinal);

        for (int i = 0; i < items.Length; i++)
        {
            ScopeCallInfo item = items[i];
            int callId = callIds[item.RequestType];

            builder.AppendLine(
                $"        public static global::LayerBase.Async.LBTask<{item.ResultType}> Call(this global::LayerBase.Scope.ScopeRef<{item.ScopeType}> scope, {item.RequestType} message)");
            builder.AppendLine("        {");
            builder.AppendLine($"            return scope.CallTask<{item.ResultType}>({callId}, message);");
            builder.AppendLine("        }");

            if (i + 1 < items.Length)
            {
                builder.AppendLine();
            }
        }

        builder.AppendLine("    }");
        builder.AppendLine("}");

        spc.AddSource("LayerBase.Scope.ScopeRefCallExtensions.g.cs", builder.ToString());
    }

    private sealed record ScopeCallInfo(string RequestType, string ScopeType, string ResultType);
}
