using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace LayerBase.Generator;

[Generator(LanguageNames.CSharp)]
public sealed class ScopeResourceGenerator : IIncrementalGenerator
{
    private const string ProvideAttributeName = "LayerBase.DI.ProvideAttribute";
    private const string FromAttributeName = "LayerBase.DI.FromAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var publishMembers = context.SyntaxProvider.ForAttributeWithMetadataName(
            ProvideAttributeName,
            static (node, _) => node is VariableDeclaratorSyntax or PropertyDeclarationSyntax,
            static (ctx, _) => GetResourceInfo(ctx, isPublish: true));

        var fromFields = context.SyntaxProvider.ForAttributeWithMetadataName(
            FromAttributeName,
            static (node, _) => node is VariableDeclaratorSyntax,
            static (ctx, _) => GetResourceInfo(ctx, isPublish: false));

        var allResources = publishMembers.Collect().Combine(fromFields.Collect());
        var compilationAndResources = context.CompilationProvider.Combine(allResources);

        context.RegisterSourceOutput(compilationAndResources,
            static (spc, pair) => Generate(spc, pair.Left, pair.Right.Left, pair.Right.Right));
    }

    private static ResourceInfo? GetResourceInfo(GeneratorAttributeSyntaxContext ctx, bool isPublish)
    {
        var attr = ctx.Attributes[0];
        var symbol = ctx.TargetSymbol;

        string? localKey = null;
        ITypeSymbol? providerType = null;

        if (isPublish)
        {
            if (attr.ConstructorArguments.Length < 1) return null;
            localKey = attr.ConstructorArguments[0].Value as string;

            var type = symbol switch
            {
                IFieldSymbol field => field.Type,
                IPropertySymbol property => property.Type,
                _ => null
            };
            if (type == null || string.IsNullOrEmpty(localKey)) return null;

            return new ResourceInfo(
                symbol.ContainingType, symbol.Name, type,
                symbol.ContainingType, localKey, true,
                symbol.Locations.FirstOrDefault() ?? Location.None,
                false);
        }
        else
        {
            var fieldSymbol = (IFieldSymbol)symbol;
            if (attr.ConstructorArguments.Length < 2) return null;

            providerType = attr.ConstructorArguments[0].Value as ITypeSymbol;
            localKey = attr.ConstructorArguments[1].Value as string;

            if (providerType == null || string.IsNullOrEmpty(localKey)) return null;

            return new ResourceInfo(
                fieldSymbol.ContainingType, fieldSymbol.Name, fieldSymbol.Type,
                providerType, localKey, false,
                fieldSymbol.Locations.FirstOrDefault() ?? Location.None,
                fieldSymbol.IsReadOnly);
        }
    }

    private static void Generate(
        SourceProductionContext spc,
        Compilation compilation,
        ImmutableArray<ResourceInfo?> publishes,
        ImmutableArray<ResourceInfo?> uses)
    {
        var validPublishes = publishes
            .Where(p => p != null)
            .Select(p => p!)
            .Where(static p => CanGeneratePartialChain(p.ContainingType))
            .ToImmutableArray();
        var validUses = uses
            .Where(p => p != null)
            .Select(p => p!)
            .Where(static p => CanGeneratePartialChain(p.ContainingType))
            .ToImmutableArray();

        if (validPublishes.Length == 0 && validUses.Length == 0)
            return;

        var publishByType = validPublishes.GroupBy(p => p.ContainingType).ToImmutableArray();
        var useByType = validUses.GroupBy(u => u.ContainingType).ToImmutableArray();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#pragma warning disable CS8600, CS8601, CS8602, CS8603, CS8604");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        foreach (var publish in validPublishes)
        {
            sb.AppendLine(
                $"[assembly: global::LayerBase.Scope.Resources.ScopeResourceExportManifestAttribute(" +
                $"typeof({publish.ProviderType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}), " +
                $"typeof({publish.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}), " +
                $"{SymbolDisplay.FormatLiteral(publish.LocalKey, quote: true)})]");
        }

        if (validPublishes.Length > 0)
        {
            sb.AppendLine();
        }

        // Generate IGeneratedScopeResourcePublisher for each type with [Provide]
        foreach (var group in publishByType)
        {
            var memberList = group.ToImmutableArray();
            AppendPartialTypeStart(
                sb,
                group.Key,
                " : global::LayerBase.Scope.Resources.IGeneratedScopeResourcePublisher");

            string indent = GetMemberIndent(group.Key);
            sb.AppendLine($"{indent}object global::LayerBase.Scope.Resources.IGeneratedScopeResourcePublisher.GetPublishedResource(int exportId)");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    switch (exportId)");
            sb.AppendLine($"{indent}    {{");

            for (int i = 0; i < memberList.Length; i++)
            {
                var member = memberList[i];
                string accessExpr = member.Name;
                sb.AppendLine($"{indent}        case {i}: return {accessExpr};");
            }

            sb.AppendLine($"{indent}        default: throw new global::System.ArgumentOutOfRangeException(nameof(exportId));");
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine($"{indent}}}");
            AppendPartialTypeEnd(sb, group.Key);
            sb.AppendLine();
        }

        // Generate IGeneratedScopeResourceConsumer for each type with [From]
        foreach (var group in useByType)
        {
            var memberList = group.ToImmutableArray();
            AppendPartialTypeStart(
                sb,
                group.Key,
                " : global::LayerBase.Scope.Resources.IGeneratedScopeResourceConsumer");

            string indent = GetMemberIndent(group.Key);
            sb.AppendLine($"{indent}void global::LayerBase.Scope.Resources.IGeneratedScopeResourceConsumer.BindScopeResource(int importId, object resource)");
            sb.AppendLine($"{indent}{{");
            sb.AppendLine($"{indent}    switch (importId)");
            sb.AppendLine($"{indent}    {{");

            for (int i = 0; i < memberList.Length; i++)
            {
                var member = memberList[i];
                string castType = member.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                sb.AppendLine($"{indent}        case {i}: {member.Name} = ({castType})resource; return;");
            }

            sb.AppendLine($"{indent}        default: throw new global::System.ArgumentOutOfRangeException(nameof(importId));");
            sb.AppendLine($"{indent}    }}");
            sb.AppendLine($"{indent}}}");
            sb.AppendLine();
            sb.AppendLine($"{indent}void global::LayerBase.Scope.Resources.IGeneratedScopeResourceConsumer.UnbindScopeResources()");
            sb.AppendLine($"{indent}{{");

            for (int i = 0; i < memberList.Length; i++)
            {
                var member = memberList[i];
                sb.AppendLine($"{indent}    {member.Name} = default!;");
            }

            sb.AppendLine($"{indent}}}");
            AppendPartialTypeEnd(sb, group.Key);
            sb.AppendLine();
        }

        // Generate resource contribution data
        sb.AppendLine("internal static class GeneratedScopeResourceContributions");
        sb.AppendLine("{");
        sb.AppendLine("    public static global::LayerBase.Scope.Resources.ScopeResourceExportContribution[] GetExports()");
        sb.AppendLine("    {");
        sb.AppendLine("        return new global::LayerBase.Scope.Resources.ScopeResourceExportContribution[]");
        sb.AppendLine("        {");

        int exportId = 0;
        foreach (var group in publishByType)
        {
            int localSlot = 0;
            foreach (var member in group)
            {
                sb.AppendLine(
                    $"            new global::LayerBase.Scope.Resources.ScopeResourceExportContribution(" +
                    $"typeof({group.Key.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}).TypeHandle, " +
                    $"typeof({member.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}).TypeHandle, " +
                    $"{SymbolDisplay.FormatLiteral(member.LocalKey, quote: true)}, {exportId++}, {localSlot++}),");
            }
        }

        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public static global::LayerBase.Scope.Resources.ScopeResourceImportContribution[] GetImports()");
        sb.AppendLine("    {");
        sb.AppendLine("        return new global::LayerBase.Scope.Resources.ScopeResourceImportContribution[]");
        sb.AppendLine("        {");

        int importId = 0;
        foreach (var group in useByType)
        {
            int localSlot = 0;
            foreach (var member in group)
            {
                sb.AppendLine(
                    $"            new global::LayerBase.Scope.Resources.ScopeResourceImportContribution(" +
                    $"typeof({group.Key.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}).TypeHandle, " +
                    $"typeof({member.ProviderType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}).TypeHandle, " +
                    $"typeof({member.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}).TypeHandle, " +
                    $"{SymbolDisplay.FormatLiteral(member.LocalKey, quote: true)}, {importId++}, {localSlot++}),");
            }
        }

        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource("ScopeResourceBindings.g.cs", sb.ToString());
    }

    private static void AppendPartialTypeStart(
        StringBuilder builder,
        INamedTypeSymbol symbol,
        string interfaceClause)
    {
        bool hasNamespace = !symbol.ContainingNamespace.IsGlobalNamespace;
        if (hasNamespace)
        {
            builder.Append("namespace ");
            builder.AppendLine(symbol.ContainingNamespace.ToDisplayString());
            builder.AppendLine("{");
        }

        int baseLevel = hasNamespace ? 1 : 0;
        AppendContainingTypesStart(builder, symbol.ContainingType, baseLevel);
        AppendTypeDeclaration(builder, symbol, baseLevel + GetContainingTypeDepth(symbol.ContainingType), interfaceClause);
        builder.AppendLine();
        AppendConstraintClauses(builder, symbol, GetIndent(baseLevel + GetContainingTypeDepth(symbol.ContainingType)));
        builder.AppendLine(GetIndent(baseLevel + GetContainingTypeDepth(symbol.ContainingType)) + "{");
    }

    private static void AppendPartialTypeEnd(StringBuilder builder, INamedTypeSymbol symbol)
    {
        bool hasNamespace = !symbol.ContainingNamespace.IsGlobalNamespace;
        int baseLevel = hasNamespace ? 1 : 0;
        int typeLevel = baseLevel + GetContainingTypeDepth(symbol.ContainingType);

        builder.AppendLine(GetIndent(typeLevel) + "}");
        AppendContainingTypesEnd(builder, symbol.ContainingType, baseLevel);
        if (hasNamespace)
        {
            builder.AppendLine("}");
        }
    }

    private static void AppendContainingTypesStart(StringBuilder builder, INamedTypeSymbol? symbol, int level)
    {
        if (symbol == null)
        {
            return;
        }

        AppendContainingTypesStart(builder, symbol.ContainingType, level);
        int typeLevel = level + GetContainingTypeDepth(symbol.ContainingType);
        AppendTypeDeclaration(builder, symbol, typeLevel, string.Empty);
        builder.AppendLine();
        AppendConstraintClauses(builder, symbol, GetIndent(typeLevel));
        builder.AppendLine(GetIndent(typeLevel) + "{");
    }

    private static void AppendContainingTypesEnd(StringBuilder builder, INamedTypeSymbol? symbol, int level)
    {
        if (symbol == null)
        {
            return;
        }

        int typeLevel = level + GetContainingTypeDepth(symbol.ContainingType);
        builder.AppendLine(GetIndent(typeLevel) + "}");
        AppendContainingTypesEnd(builder, symbol.ContainingType, level);
    }

    private static void AppendTypeDeclaration(
        StringBuilder builder,
        INamedTypeSymbol symbol,
        int level,
        string interfaceClause)
    {
        string indent = GetIndent(level);
        builder.Append(indent);
        builder.Append(GetAccessibility(symbol.DeclaredAccessibility));
        builder.Append(' ');
        builder.Append(GetTypeModifier(symbol));
        builder.Append("partial ");
        builder.Append(GetTypeKeyword(symbol));
        builder.Append(' ');
        builder.Append(symbol.Name);
        builder.Append(GetTypeParameterList(symbol));
        builder.Append(interfaceClause);
    }

    private static void AppendConstraintClauses(StringBuilder builder, INamedTypeSymbol symbol, string indent)
    {
        foreach (ITypeParameterSymbol typeParameter in symbol.TypeParameters)
        {
            string constraint = BuildConstraintClause(typeParameter);
            if (constraint.Length != 0)
            {
                builder.Append(indent);
                builder.Append("    ");
                builder.AppendLine(constraint);
            }
        }
    }

    private static string BuildConstraintClause(ITypeParameterSymbol typeParameter)
    {
        var parts = new List<string>();

        if (typeParameter.HasReferenceTypeConstraint)
        {
            parts.Add(typeParameter.ReferenceTypeConstraintNullableAnnotation == NullableAnnotation.Annotated
                ? "class?"
                : "class");
        }

        if (typeParameter.HasUnmanagedTypeConstraint)
        {
            parts.Add("unmanaged");
        }
        else if (typeParameter.HasValueTypeConstraint)
        {
            parts.Add("struct");
        }

        foreach (ITypeSymbol constraintType in typeParameter.ConstraintTypes)
        {
            parts.Add(constraintType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
        }

        if (typeParameter.HasNotNullConstraint)
        {
            parts.Add("notnull");
        }

        if (typeParameter.HasConstructorConstraint)
        {
            parts.Add("new()");
        }

        return parts.Count == 0
            ? string.Empty
            : $"where {typeParameter.Name} : {string.Join(", ", parts)}";
    }

    private static string GetTypeParameterList(INamedTypeSymbol symbol)
    {
        return symbol.TypeParameters.Length == 0
            ? string.Empty
            : "<" + string.Join(", ", symbol.TypeParameters.Select(static parameter => parameter.Name)) + ">";
    }

    private static int GetContainingTypeDepth(INamedTypeSymbol? symbol)
    {
        int depth = 0;
        for (INamedTypeSymbol? current = symbol; current != null; current = current.ContainingType)
        {
            depth++;
        }

        return depth;
    }

    private static string GetMemberIndent(INamedTypeSymbol symbol)
    {
        int level = (symbol.ContainingNamespace.IsGlobalNamespace ? 0 : 1)
                    + GetContainingTypeDepth(symbol.ContainingType)
                    + 1;
        return GetIndent(level);
    }

    private static string GetIndent(int level)
    {
        return new string(' ', level * 4);
    }

    private static string GetAccessibility(Accessibility accessibility)
    {
        return accessibility switch
        {
            Accessibility.Public => "public",
            Accessibility.Internal => "internal",
            Accessibility.Private => "private",
            Accessibility.Protected => "protected",
            Accessibility.ProtectedAndInternal => "private protected",
            Accessibility.ProtectedOrInternal => "protected internal",
            _ => "internal"
        };
    }

    private static string GetTypeModifier(INamedTypeSymbol symbol)
    {
        if (symbol.IsStatic)
        {
            return "static ";
        }

        if (symbol.IsAbstract)
        {
            return "abstract ";
        }

        if (symbol.IsSealed && symbol.TypeKind == TypeKind.Class)
        {
            return "sealed ";
        }

        return string.Empty;
    }

    private static string GetTypeKeyword(INamedTypeSymbol symbol)
    {
        if (symbol.IsRecord)
        {
            return symbol.TypeKind == TypeKind.Struct ? "record struct" : "record";
        }

        return symbol.TypeKind == TypeKind.Struct ? "struct" : "class";
    }

    private static bool CanGeneratePartialChain(INamedTypeSymbol symbol)
    {
        for (INamedTypeSymbol? current = symbol; current != null; current = current.ContainingType)
        {
            if (!IsPartialType(current))
            {
                return false;
            }
        }

        return true;
    }

    private static bool IsPartialType(INamedTypeSymbol symbol)
    {
        return symbol.DeclaringSyntaxReferences
            .Select(static reference => reference.GetSyntax())
            .OfType<TypeDeclarationSyntax>()
            .Any(static syntax => syntax.Modifiers.Any(SyntaxKind.PartialKeyword));
    }

    private sealed class ResourceInfo
    {
        public ResourceInfo(
            INamedTypeSymbol containingType, string name, ITypeSymbol type,
            ITypeSymbol providerType, string localKey, bool isPublish,
            Location? location, bool isReadOnly)
        {
            ContainingType = containingType;
            Name = name;
            Type = type;
            ProviderType = providerType;
            LocalKey = localKey;
            IsPublish = isPublish;
            Location = location;
            IsReadOnly = isReadOnly;
        }

        public INamedTypeSymbol ContainingType { get; }
        public string Name { get; }
        public ITypeSymbol Type { get; }
        public ITypeSymbol ProviderType { get; }
        public string LocalKey { get; }
        public bool IsPublish { get; }
        public Location? Location { get; }
        public bool IsReadOnly { get; }
    }
}
