using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace LayerBase.Generator;

[Generator(LanguageNames.CSharp)]
public sealed class ScopeResourceGenerator : IIncrementalGenerator
{
    private const string ProvideAttributeName = "LayerBase.DI.ProvideAttribute";
    private const string FromAttributeName = "LayerBase.DI.FromAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var publishMembers = context.SyntaxProvider.ForAttributeWithMetadataName(
            ProvideAttributeName,
            static (node, _) => node is FieldDeclarationSyntax or PropertyDeclarationSyntax,
            static (ctx, _) => GetResourceInfo(ctx, isPublish: true));

        var fromFields = context.SyntaxProvider.ForAttributeWithMetadataName(
            FromAttributeName,
            static (node, _) => node is FieldDeclarationSyntax,
            static (ctx, _) => GetResourceInfo(ctx, isPublish: false));

        var allResources = publishMembers.Collect().Combine(fromFields.Collect());
        var compilationAndResources = context.CompilationProvider.Combine(allResources);

        context.RegisterSourceOutput(compilationAndResources,
            static (spc, pair) => Generate(spc, pair.Left, pair.Right.Left, pair.Right.Right));
    }

    private static ResourceInfo? GetResourceInfo(GeneratorAttributeSyntaxContext ctx, bool isPublish)
    {
        var attr = ctx.Attributes[0];
        var symbol = ctx.TargetSymbol;

        string? localKey = null;
        ITypeSymbol? providerType = null;

        if (isPublish)
        {
            if (attr.ConstructorArguments.Length < 1) return null;
            localKey = attr.ConstructorArguments[0].Value as string;

            var type = symbol switch
            {
                IFieldSymbol field => field.Type,
                IPropertySymbol property => property.Type,
                _ => null
            };
            if (type == null || string.IsNullOrEmpty(localKey)) return null;

            return new ResourceInfo(
                symbol.ContainingType, symbol.Name, type,
                symbol.ContainingType, localKey, true,
                symbol.Locations.FirstOrDefault() ?? Location.None,
                false);
        }
        else
        {
            var fieldSymbol = (IFieldSymbol)symbol;
            if (attr.ConstructorArguments.Length < 2) return null;

            providerType = attr.ConstructorArguments[0].Value as ITypeSymbol;
            localKey = attr.ConstructorArguments[1].Value as string;

            if (providerType == null || string.IsNullOrEmpty(localKey)) return null;

            return new ResourceInfo(
                fieldSymbol.ContainingType, fieldSymbol.Name, fieldSymbol.Type,
                providerType, localKey, false,
                fieldSymbol.Locations.FirstOrDefault() ?? Location.None,
                fieldSymbol.IsReadOnly);
        }
    }

    private static void Generate(
        SourceProductionContext spc,
        Compilation compilation,
        ImmutableArray<ResourceInfo?> publishes,
        ImmutableArray<ResourceInfo?> uses)
    {
        var validPublishes = publishes.Where(p => p != null).Select(p => p!).ToImmutableArray();
        var validUses = uses.Where(p => p != null).Select(p => p!).ToImmutableArray();

        if (validPublishes.Length == 0 && validUses.Length == 0)
            return;

        var publishByType = validPublishes.GroupBy(p => p.ContainingType).ToImmutableArray();
        var useByType = validUses.GroupBy(u => u.ContainingType).ToImmutableArray();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#pragma warning disable CS8600, CS8601, CS8602, CS8603, CS8604");
        sb.AppendLine("using System;");
        sb.AppendLine("using LayerBase.Scope.Resources;");
        sb.AppendLine();

        // Generate IGeneratedScopeResourcePublisher for each type with [Provide]
        foreach (var group in publishByType)
        {
            var typeName = group.Key.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var memberList = group.ToImmutableArray();

            sb.AppendLine($"partial class {typeName} : IGeneratedScopeResourcePublisher");
            sb.AppendLine("{");
            sb.AppendLine("    object IGeneratedScopeResourcePublisher.GetPublishedResource(int exportId)");
            sb.AppendLine("    {");
            sb.AppendLine("        switch (exportId)");
            sb.AppendLine("        {");

            for (int i = 0; i < memberList.Length; i++)
            {
                var member = memberList[i];
                string accessExpr = member.Name;
                sb.AppendLine($"            case {i}: return {accessExpr};");
            }

            sb.AppendLine("            default: throw new ArgumentOutOfRangeException(nameof(exportId));");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        // Generate IGeneratedScopeResourceConsumer for each type with [From]
        foreach (var group in useByType)
        {
            var typeName = group.Key.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
            var memberList = group.ToImmutableArray();

            sb.AppendLine($"partial class {typeName} : IGeneratedScopeResourceConsumer");
            sb.AppendLine("{");
            sb.AppendLine("    void IGeneratedScopeResourceConsumer.BindScopeResource(int importId, object resource)");
            sb.AppendLine("    {");
            sb.AppendLine("        switch (importId)");
            sb.AppendLine("        {");

            for (int i = 0; i < memberList.Length; i++)
            {
                var member = memberList[i];
                string castType = member.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                sb.AppendLine($"            case {i}: {member.Name} = ({castType})resource; return;");
            }

            sb.AppendLine("            default: throw new ArgumentOutOfRangeException(nameof(importId));");
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine();
            sb.AppendLine("    void IGeneratedScopeResourceConsumer.UnbindScopeResources()");
            sb.AppendLine("    {");

            for (int i = 0; i < memberList.Length; i++)
            {
                var member = memberList[i];
                sb.AppendLine($"        {member.Name} = default!;");
            }

            sb.AppendLine("    }");
            sb.AppendLine("}");
            sb.AppendLine();
        }

        // Generate resource contribution data
        sb.AppendLine("internal static class GeneratedScopeResourceContributions");
        sb.AppendLine("{");
        sb.AppendLine("    public static ScopeResourceExportContribution[] GetExports()");
        sb.AppendLine("    {");
        sb.AppendLine("        return new ScopeResourceExportContribution[]");
        sb.AppendLine("        {");

        int exportId = 0;
        foreach (var group in publishByType)
        {
            foreach (var member in group)
            {
                sb.AppendLine(
                    $"            new ScopeResourceExportContribution(" +
                    $"typeof({group.Key.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}).TypeHandle, " +
                    $"typeof({member.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}).TypeHandle, " +
                    $"\"{member.LocalKey}\", {exportId++}),");
            }
        }

        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public static ScopeResourceImportContribution[] GetImports()");
        sb.AppendLine("    {");
        sb.AppendLine("        return new ScopeResourceImportContribution[]");
        sb.AppendLine("        {");

        int importId = 0;
        foreach (var group in useByType)
        {
            foreach (var member in group)
            {
                sb.AppendLine(
                    $"            new ScopeResourceImportContribution(" +
                    $"typeof({group.Key.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}).TypeHandle, " +
                    $"typeof({member.ProviderType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}).TypeHandle, " +
                    $"typeof({member.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}).TypeHandle, " +
                    $"\"{member.LocalKey}\", {importId++}),");
            }
        }

        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource("ScopeResourceBindings.g.cs", sb.ToString());
    }

    private sealed class ResourceInfo
    {
        public ResourceInfo(
            INamedTypeSymbol containingType, string name, ITypeSymbol type,
            ITypeSymbol providerType, string localKey, bool isPublish,
            Location? location, bool isReadOnly)
        {
            ContainingType = containingType;
            Name = name;
            Type = type;
            ProviderType = providerType;
            LocalKey = localKey;
            IsPublish = isPublish;
            Location = location;
            IsReadOnly = isReadOnly;
        }

        public INamedTypeSymbol ContainingType { get; }
        public string Name { get; }
        public ITypeSymbol Type { get; }
        public ITypeSymbol ProviderType { get; }
        public string LocalKey { get; }
        public bool IsPublish { get; }
        public Location? Location { get; }
        public bool IsReadOnly { get; }
    }
}